### ISSUE TITLE
Couldn't load plugin 'shapetools' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by antoniolocandro** [NationalSecurityAgency/qgis-shapetools-plugin#51]
Got the following error when using the plugin when both QGIS and QGIS dev are installed alongside using Osgeo4w, this happens with 
GDAL/OGR version
3.9.0dev-b2015f85f9

I don't know enough coding to be able to check where the gdal import happens in the plugin to review if its a plugin issue or not

ModuleNotFoundError: No module named '_gdal' 
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 666, in _load_unlocked
  File "", line 565, in module_from_spec
  File "", line 1173, in create_module
  File "", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

**Comment by hamiltoncj** [comment]
There is nothing in that error message related to the Shape Tools plugin. Shape Tools isn't causing it. This looks like an OSGeo4W installation issue. You may want to uninstall everything and then reinstall the software. I'm going to close the ticket because I can only help with issues related to my plugins. Unless you are a developer, I wouldn't install the dev versions of software. I don't ever install them.
